import os

S3_BUCKET_NAME = os.environ["S3_BUCKET_NAME"]
PROCESSOR_LAMBDA_FUNCTION_NAME = os.environ["PROCESSOR_LAMBDA_FUNCTION_NAME"]
MODEL_CONFIG_PATH = os.environ["MODEL_CONFIG_PATH"]

# Kintone API Configuration
KINTONE_API_TOKEN = os.environ["KINTONE_API_TOKEN"]
KINTONE_SUBDOMAIN = os.environ["KINTONE_SUBDOMAIN"]
KINTONE_APP_ID = os.environ["KINTONE_APP_ID"]
KINTONE_DATA_FIELD_CODE = os.environ["KINTONE_DATA_FIELD_CODE"]
KINTONE_UPDATE_FIELD_CODE = os.environ["KINTONE_UPDATE_FIELD_CODE"]

STAGE = os.environ["STAGE"]

if STAGE == "local":
    S3_BUCKET_NAME = "localstack-kajima-uploaded-image"
    PROCESSOR_LAMBDA_FUNCTION_NAME = "localstack-kajima-batch-processor-api"

OAUTH_COGNITO_CLIENT_ID = os.environ["OAUTH_COGNITO_CLIENT_ID"]
OAUTH_COGNITO_CLIENT_SECRET = os.environ["OAUTH_COGNITO_CLIENT_SECRET"]
OAUTH_COGNITO_DOMAIN = os.environ["OAUTH_COGNITO_DOMAIN"]
OAUTH_COGNITO_USER_POOL_ID = os.environ["OAUTH_COGNITO_USER_POOL_ID"]
OAUTH_COGNITO_AWS_REGION = os.environ["OAUTH_COGNITO_AWS_REGION"]
